### ISSUE TITLE
Periodicity along diagonal

### ISSUE THREAD

**Issue by grandseiken** [ashima/webgl-noise#15] opened 2015-08-18 22:39 UTC
Hey, this might be a dupe of [issue 10](https://github.com/ashima/webgl-noise/issues/10) but the links are broken in that one so I couldn't be sure. Apologies if so.

It seems like both the 2D and 3D simplex noise functions are periodic with respect to a particular diagonal direction. The problem is not quite so obvious in 2D, but it's definitely still there. I tried various fixes mentioned in other issues without luck. Did I do something wrong?

In the samples below I zoomed out a lot to show the problem but it's also quite noticeable in real situations. Increasing the period would be fine for my use case I guess, it just seems very small at the moment.

I tried changing the value of 289 used in the permutation to something much higher, which _did_ fix the periodicity problem, but it also introduced discontinuities in the noise function along diagonal lines. I guess it needs to be a real permutation polynomial rather than some number I made up, but I'm not sure how those values were constructed in the first place.

Here are code samples and results for both cases. It's just the fragment shader and I'm rendering a quad over the whole screen.

``` glsl
#include "noise3D.glsl"

out vec4 output_colour;

void main()
{
  highp vec3 seed = vec3(0, gl_FragCoord.xy) / 2;
  highp float n = snoise(seed);
  float v = clamp((n + 1) / 2, 0, 1);
  output_colour = vec4(v, v, v, 1);
}
```

![screenshot](https://cloud.githubusercontent.com/assets/6506599/9344282/5886dc2c-45ff-11e5-9714-4b0a23963caf.png)

``` glsl
#include "noise2D.glsl"

out vec4 output_colour;

void main()
{
  highp float n = snoise(gl_FragCoord.xy / 2);
  float v = clamp((n + 1) / 2, 0, 1);
  output_colour = vec4(v, v, v, 1);
}
```

![screenshot2d](https://cloud.githubusercontent.com/assets/6506599/9344326/c0cc948e-45ff-11e5-9ed5-178fa090c16e.png)

**Comment by stegu** [comment] 2015-08-19 13:19
Yes, this is a known issue, and unfortunately it's a tough nut to crack.

Planar cuts through 3D noise are problematic, even for the simplex grid.
(It's much worse than this for the "classic" axis-aligned grid.) Try adding
some small slope in z to the cut, and the problem might be much less
pronounced:
n = snoise(vec3(coords.xy, coords.x*0.2);
Even using "n = snoise(coords.xy, 0.0)" instead of n=snoise(0.0, coords.xy)
could have a positive effect. X, Y and Z are treated slightly differently
in the hash value computation.

As for the 2D case, well, the permutation is far from optimal - it's not
even particularly good. We just settled for something that was "good
enough" for most practical purposes and lent itself to implementation
within the limited integer range of 32-bit float values. Our original
article contains details on how the permutation polynomial is constructed,
and why we chose 289 (17*17) as the period. A larger period is perfectly
possible, and there may be polynomials that make less objectionable visual
patterns, but it's tricky to find them, and the choices are not all that
many if you want to use "float" which has an effective integer range
equivalent to 23 bits. (Larger numbers chop off some of the least
significant bits in the integer, which makes any hash function break down.)
Switching to 32-bit integers would make the problem a lot easier, but our
goal was to keep it compatible with OpenGL ES and WebGL, where integers are
still not available in most implementations. A real 32-bit integer data
type and logical operations (AND, OR, XOR) would make it possible to use a
more traditional integer hash function, of which there are many variants
published by other authors.

Some links that may or may not be useful to you:

www.cs.utah.edu/~aek/research/noise.pdf
This article points out the cause of the problem you found, but implements
a fix using permutation tables, which are undesirable for SIMD
implementations because of memory accesses.

https://briansharpe.wordpress.com/2011/10/01/gpu-texture-free-noise/
This also points to the problem you found, but offers no solution.

https://umbcgaim.wordpress.com/2010/07/01/gpu-random-numbers/
Presents a solution requiring 32-bit integer math. (Lots of similar hash
functions, some even simpler, exist in literature.)

www.sinfocol.org/archivos/2009/11/Goulburn06.pdf
Presents the Goulburn function, which has very good "randomness" but takes
a fair amout of cycles to compute. It also uses an in-memory table, even
though its use might be optional in this particular application.

Note that avoiding memory accesses at all costs is not always a good idea.
The traditional method of using a permutation table lends itself quite well
to implementation as a texture lookup. If you have texture bandwidth to
spare, a texture access might actually be faster than a permutation
function on current generation GPUs. You can compare the speed in this test:
http://www.itn.liu.se/~stegu/simplexnoise/GLSL-noise-vs-noise.zip
http://www.itn.liu.se/~stegu/simplexnoise/GLSL-noise-vs-noise-Win32.zip

   /Stefan Gustavson

**Comment by grandseiken** [comment] 2015-08-19 18:53
Hey, thank you for your detailed reply.

It seems like using any axis-aligned plane (`snoise(coords.xy, 0)`, `snoise(0, coords.xy)`, `snoise(coords.x, 0, coords.y)`) has just as bad a problem. I didn't notice any subjective improvement swapping between these (I had tried already based on a comment in a different issue).

Adding a small z slope actually helps a fair bit: the noise is no longer so obviously and drastically periodic, but general recurring patterns are still fairly obvious, and additionally the general patterns now seem to repeat in two directions instead than just one.

Thanks for the other notes and links. I'll probably end up doing something with integers or using a texture lookup.

Just one more question: what are you referring to by "our original article"? I thought you might mean [this](http://webstaff.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf) but it doesn't appear to contain anything on permutation polynomials. Cheers!

**Comment by stegu** [comment] 2015-08-20 22:06
> what are you referring to by "our original article"?

Sorry for the confusion, I meant the write-up by Ian McEwan and myself on
this particular implementation of noise, from Journal of Graphics Tools:
http://www.itn.liu.se/~stegu/jgt2012/
There is a link to it on the Ashima "webgl-noise" wiki page:
https://github.com/ashima/webgl-noise/wiki

**Comment by stegu** [comment] 2020-10-14 08:33
The thread is a detailed description of problems that still exist in the implementation, so I'm keeping it open.

**Comment by stegu** [comment] 2021-06-29 09:29
Ian McEwan and I are in the process of writing new noise functions, and in that process we found a better permutation polynomial that does not cause these ugly diagonal streaks. I have now retroactively changed the permutation polynomial across the board for all these old functions as well. It's only a matter of changing a "1.0" to "6.0". Sad that it took this long to find that simple remedy, but finding permutations to generate "apparent randomness" are a really tricky subject where there is little relevant previous work.

**Comment by stegu** [comment] 2021-11-26 09:40
The problem seems to have gone "poof" with that slight change to the permutation polynomial, so I'm closing this thread.

**Closed by stegu** 2021-11-26 09:40 UTC

**Comment by andrewbaxter** [comment] 2025-06-13 15:35
Has anything happened regarding this since? Using https://github.com/ashima/webgl-noise/blob/master/src/noise2D.glsl I feel like I'm still getting more or less the same pattern:

```
precision highp float;
precision highp int;

/////
//
// Description : Array and textureless GLSL 2D simplex noise function.
//      Author : Ian McEwan, Ashima Arts.
//  Maintainer : stegu
//     Lastmod : 20110822 (ijm)
//     License : Copyright (C) 2011 Ashima Arts. All rights reserved.
//               Distributed under the MIT License. See LICENSE file.
//               https://github.com/ashima/webgl-noise
//               https://github.com/stegu/webgl-noise
// 

vec3 mod289(vec3 x) {
  return x - floor(x * (1.0 / 289.0)) * 289.0;
}

vec2 mod289(vec2 x) {
  return x - floor(x * (1.0 / 289.0)) * 289.0;
}

vec3 permute(vec3 x) {
  return mod289(((x*34.0)+10.0)*x);
}

float snoise(vec2 v)
  {
  const vec4 C = vec4(0.211324865405187,  // (3.0-sqrt(3.0))/6.0
                      0.366025403784439,  // 0.5*(sqrt(3.0)-1.0)
                     -0.577350269189626,  // -1.0 + 2.0 * C.x
                      0.024390243902439); // 1.0 / 41.0
// First corner
  vec2 i  = floor(v + dot(v, C.yy) );
  vec2 x0 = v -   i + dot(i, C.xx);

// Other corners
  vec2 i1;
  //i1.x = step( x0.y, x0.x ); // x0.x > x0.y ? 1.0 : 0.0
  //i1.y = 1.0 - i1.x;
  i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);
  // x0 = x0 - 0.0 + 0.0 * C.xx ;
  // x1 = x0 - i1 + 1.0 * C.xx ;
  // x2 = x0 - 1.0 + 2.0 * C.xx ;
  vec4 x12 = x0.xyxy + C.xxzz;
  x12.xy -= i1;

// Permutations
  i = mod289(i); // Avoid truncation effects in permutation
  vec3 p = permute( permute( i.y + vec3(0.0, i1.y, 1.0 ))
		+ i.x + vec3(0.0, i1.x, 1.0 ));

  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);
  m = m*m ;
  m = m*m ;

// Gradients: 41 points uniformly over a line, mapped onto a diamond.
// The ring size 17*17 = 289 is close to a multiple of 41 (41*7 = 287)

  vec3 x = 2.0 * fract(p * C.www) - 1.0;
  vec3 h = abs(x) - 0.5;
  vec3 ox = floor(x + 0.5);
  vec3 a0 = x - ox;

// Normalise gradients implicitly by scaling m
// Approximation of: m *= inversesqrt( a0*a0 + h*h );
  m *= 1.79284291400159 - 0.85373472095314 * ( a0*a0 + h*h );

// Compute final noise value at P
  vec3 g;
  g.x  = a0.x  * x0.x  + h.x  * x0.y;
  g.yz = a0.yz * x12.xz + h.yz * x12.yw;
  return 130.0 * dot(m, g);
}
/////

void main() {
    gl_FragColor = vec4(vec3(snoise(gl_FragCoord.xy)), 1.);
}
```
I just grabbed the code from `master` today.  FragCoord runs from 0-1080p.  Also FWIW the source file says `Lastmod: 20110822` which I assume is wrong now.

**Comment by stegu** [comment] 2025-06-14 05:49
The Ashima repo is no longer being maintained. The code at my fork stegu/webgl-noise should be the same, though.

The 2-D noise is really not pretty all on its own in a single component. If you want better randomness, I recommend using a 2-D slice through 3-D noise. Don't pick an axis-aligned plane, and you should see a lot less problems.

If you want a better 2-D hash with less visible artifacts, and if you are aiming for higher end platforms with good integer support, there are some crypto-style hashes you could try. Note that using integers and bit-level operations is still not supported on some GPUs, and even when supported it's hideously slow on some low end devices.

Unfortunately, I have been struck with brain fog from post-Covid since 2020, so I have a lot less time and energy to spend on coding these days. I'm still unable to work full time, and my brain fatigues much too easily. It's getting better, but I might never recover completely. I'm not feeling stupid, but I can't maintain focus for nearly as long as I used to.

This Shadertoy demo has a few alternative hashes for you to try if you want to experiment:

https://www.shadertoy.com/view/MfccWr

**Comment by andrewbaxter** [comment] 2025-06-14 06:19
Oh thanks! That's pretty clear. And no worries! I was just wondering if I missed something above.

**Comment by unicomp21** [comment] 2025-06-14 13:52
I think all of @stegu beautiful work is in here too?

https://github.com/Auburn/FastNoise2

**Comment by unicomp21** [comment] 2025-06-14 13:54
@stegu not sure if this could help or not ...

From my experience, alpha can definitely be trained, like a muscle.
https://choosemuse.com/

**Comment by unicomp21** [comment] 2025-06-14 13:55
https://www.youtube.com/@CodyRallMD

^cody is a trained doctor/MD

**Comment by stegu** [comment] 2025-06-15 14:20
Thanks for your concern and the kind suggestion, but no, I tried training
"brain stamina", and it doesn't help. The problem seems to be (still
unverified but plausible) that the Covid-19 virus somehow damaged the
mitochondria of existing neurons and stunted the production of some
necessary signal substances. Some production remains, and because there is
a buffer (humans can temporarily use more than what is produced), I can
still be smart and move about for shorter periods, but I need to pace
myself carefully and take frequent breaks. During exertion (mental or
physical), the production is supposed to increase. Mine doesn't, for some
unknown reason. When my buffer is depleted, it takes me hours to recharge
and get my brain and body capable of working at normal speed again. It's
like hitting a wall and suddenly becoming slow and weak. Stupid, clumsy,
dead tired. It's hard to describe.
This depletion happens from physical exertion as well as mental, with the
same symptoms from both. Training doesn't help, sadly, and I can't even get
proper physical exercise - I lose power and coordination long before I get
exhausted from muscle fatigue.

Fortunately, mitochondria are replaced over time even in neurons that don't
replenish, so this will pass in a few years. Probably. Unless the virus is
still in there somehow, wreaking havoc with my systems and damaging the
fresh mitochondria as well. A weakened but over-sensitive immune system
seems to suggest that there are more things going on with this dysautonomy.

(This was a weird thing to put in a Github comment...)

**Comment by unicomp21** [comment] 2025-06-15 17:18
Lol, much is weird these days.  Be well!
